import type { PersonalProject } from "./types";

/**
 * My own apps, my business site, and community builds.
 *
 * `live: false` means the app depends on a Supabase project that's no longer
 * running — the site itself is left up but will error on data calls. Those
 * projects lean on `demoSteps` (a scripted click-through built from real
 * screenshots) instead of a working login, so the app is still legible to a
 * visitor. `live: true` projects have no such dependency and still work.
 *
 * See soul.md at the repo root for the full convention before adding one.
 */
export const PERSONAL_PROJECTS: PersonalProject[] = [
  {
    kind: "personal",
    slug: "lucky-lasso",
    name: "Lucky Lasso",
    tagline: "Mobile NA beverage vending for community events",
    url: "https://luckylassoaz.com",
    repoUrl: "https://github.com/vrostbyte/luckylassoaz",
    live: false,
    stack: ["Next.js", "Supabase", "Tailwind CSS", "Resend", "Vercel"],
    category: "business",
    status: "ARCHIVED",
    audience: "Event organizers, school athletic programs, and community gatherings in the Phoenix metro area",
    description:
      "The digital storefront for Lucky Lasso LLC. Handles event booking inquiries, menu proposals, quoting, and client messaging. The backend manages the full event lifecycle from initial inquiry through day-of logistics. The business itself started life as a completely different concept — see Lucky Lasso Bingo below for the pivot.",
    highlights: [
      "Full event pipeline: inquiry, quote, menu proposal, booking, messaging",
      "Arizona LLC with Maricopa County Type 2 mobile food permit",
      "Custom vending cart with integrated hand-wash sink for health compliance",
      "Client portal with event code access for real-time coordination",
      "Pivoted from an entirely different business concept (a bingo/trivia platform) once the beverage-vending idea proved out",
    ],
    color: "#F59E0B",
    icon: "beer",
    infra: "Dedicated Supabase project (production business data kept isolated) — retired, so the live booking flow no longer runs.",
    screenshots: [
      { src: "/screenshots/lasso-hero.png", caption: "Landing page and brand presence" },
      { src: "/screenshots/lasso-booking.png", caption: "Event booking inquiry flow" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/lasso-hero.png",
        title: "Landing page",
        caption: "A visitor lands on the brand site and sees the menu, service area, and a book-now CTA.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/lasso-booking.png",
        title: "Booking inquiry",
        caption: "They submit an event date, guest count, and venue — this kicks off a quote request instead of an instant checkout, since every event gets a custom menu proposal. Behind the scenes it lands in an admin pipeline (inquiry → quote sent → booked → day-of) so nothing falls through the cracks between events.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "myflagcoach-v2",
    name: "MyFlagCoach v2",
    tagline: "Flag football coaching and play management platform",
    url: "https://myflagcoach.joshjgriffith.dev",
    repoUrl: "https://github.com/vrostbyte/myflagcoach-v2",
    live: false,
    stack: ["Next.js", "Supabase", "Tailwind CSS", "Vercel"],
    category: "app",
    status: "ARCHIVED",
    audience: "Youth flag football coaches, league coordinators, and team staff managing plays, rosters, and game plans",
    description:
      "A full coaching platform for flag football. Coaches build playbooks with visual play diagrams, manage rosters across seasons, plan practices with linked drills, run game day with wristband-mapped play sheets, and track play-by-play results. Version 2 is a ground-up rebuild focused on mobile-first workflows.",
    highlights: [
      "27-table relational database: teams, players, seasons, playbooks, formations, games, chat, announcements",
      "Visual play diagramming with formation data stored as JSON",
      "Game plans with wristband color/number mapping for sideline use",
      "Team chat, announcements with reactions/comments, practice attendance tracking",
      "Shared access tokens with scoped permissions for parents and assistant coaches",
      "V2 replaced an earlier no-build-step React prototype (script tags + a single component) with a proper Next.js/Supabase architecture",
    ],
    color: "#3B82F6",
    icon: "flag",
    infra: "Supabase (public schema) + shared project with Periwinkel (tripatlas schema) — retired.",
    screenshots: [
      { src: "/screenshots/myflagcoach-login.png", caption: "Sign-in screen" },
      { src: "/screenshots/flagcoach-dashboard.png", caption: "Team dashboard and overview" },
      { src: "/screenshots/flagcoach-playdesigner.png", caption: "Visual play designer with formation diagram" },
      { src: "/screenshots/flagcoach-playbook.png", caption: "Playbook list with play cards" },
      { src: "/screenshots/flagcoach-gameplan.png", caption: "Game plan with wristband mapping" },
      { src: "/screenshots/flagcoach-mobile.png", caption: "Mobile play sheet for sideline use" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/myflagcoach-login.png",
        title: "Sign in",
        caption: "A coach starts at the real sign-in screen — this one's a live capture, not a mockup. Everything past this point (the backend it authenticates against) is retired, so the rest of the walkthrough is narrated from the real feature set instead of live screens.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/flagcoach-dashboard.png",
        title: "Team dashboard",
        caption: "A coach signs in to their team dashboard — roster, upcoming games, and recent activity at a glance.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/flagcoach-playdesigner.png",
        title: "Play designer",
        caption: "The play designer stores each route and formation as structured JSON, not a flat image, so plays can be searched, reused, and remixed across the playbook.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/flagcoach-gameplan.png",
        title: "Game plan & wristbands",
        caption: "Before kickoff, the coach builds a game plan and maps each play to a wristband color/number combo the QB can read at a glance.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/flagcoach-mobile.png",
        title: "Sideline, on a phone",
        caption: "On game day the whole thing collapses to a mobile play sheet built for one-handed sideline use.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "periwinkel",
    name: "Periwinkel",
    tagline: "Collaborative trip planning for group travel",
    url: "https://periwinkel.app",
    repoUrl: "https://github.com/vrostbyte/tripatlas",
    live: false,
    stack: ["Next.js", "Supabase", "Tailwind CSS", "Resend", "Leaflet", "Vercel"],
    category: "app",
    status: "ARCHIVED",
    audience: "Trip organizers (especially teachers and group leaders) who need to coordinate itineraries, share updates with parents, and manage access for participants",
    description:
      "A trip management app built for group travel coordination, one codebase serving three different views: a subway-map-style Trip Viewer for parents and students, an offline-capable Lead Portal the trip leader updates from the road, and a full desktop Trip Manager for building the itinerary ahead of time. Originally built for Taylor's school travel program.",
    highlights: [
      "Role-based access: owner, lead, viewer, plus anonymous access via codes",
      "Ordered stop itineraries with GPS, scheduled/actual times, and photo galleries",
      "Subway-map-style timeline as the hero visualization for trip progress",
      "Lead Portal designed for offline use and low international data usage",
      "Access code system with rate limiting, expiration, and lockout protection",
      "Runs on shared Supabase instance using isolated 'tripatlas' schema",
    ],
    color: "#8B5CF6",
    icon: "compass",
    infra: "Supabase (tripatlas schema on shared MyFlagCoach project) + Resend for emails — retired.",
    screenshots: [
      { src: "/screenshots/periwinkel-code-entry.png", caption: "Trip code entry — how parents get in" },
      { src: "/screenshots/periwinkel-login.png", caption: "Trip leader sign-in" },
      { src: "/screenshots/periwinkel-overview.png", caption: "Trip overview with itinerary" },
      { src: "/screenshots/periwinkel-map.png", caption: "Map view with stop pins" },
      { src: "/screenshots/periwinkel-mobile.png", caption: "Mobile stop detail with photos" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/periwinkel-code-entry.png",
        title: "Sharing without an account",
        caption: "Parents get a short access code instead of an account — enter it here and get a read-only view of the trip, no signup required. This screen is a live capture; it needs no backend to render.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/periwinkel-login.png",
        title: "Trip leader sign in",
        caption: "The trip leader signs in separately to build and update the itinerary. Also a live capture — the app's shell renders fine, it's the data behind login that's retired.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/periwinkel-overview.png",
        title: "Trip overview",
        caption: "A trip lead builds an itinerary of ordered stops — each with a scheduled time, GPS pin, and notes.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/periwinkel-map.png",
        title: "Map view",
        caption: "The itinerary renders as a map with pins in order, so anyone can see where the group is headed next.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/periwinkel-mobile.png",
        title: "On the road",
        caption: "Chaperones check the mobile view for the next stop's time and any photos posted from the current one.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "pulsemap",
    name: "PulseMap.org",
    tagline: "Geographic data visualization and community mapping",
    url: "https://pulsemap.org",
    live: true,
    stack: ["React", "Mapbox GL", "Tailwind CSS", "Vercel"],
    category: "app",
    status: "LIVE",
    audience: "Community organizers and anyone interested in geographic data visualization",
    description:
      "An interactive mapping platform that turns geographic data into visual layers. No backend database needed. Pulls data from external APIs and renders it on Mapbox with custom styling and interactivity.",
    highlights: [
      "Pure frontend: API calls + Mapbox rendering, no database",
      "Real-time data layer rendering with custom map styles",
      "Interactive tooltips and filtering by data attributes",
    ],
    color: "#10B981",
    icon: "map-pin",
    infra: "No database. Frontend-only with external API integrations — unaffected by the Supabase retirement, still fully live.",
    screenshots: [
      { src: "/screenshots/pulsemap-main.png", caption: "Main map view with data layers" },
      { src: "/screenshots/pulsemap-filtered.png", caption: "Filtered view with interactive tooltips" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/pulsemap-main.png",
        title: "Main map",
        caption: "Data layers render straight from external APIs onto a styled Mapbox canvas — nothing is stored server-side.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/pulsemap-filtered.png",
        title: "Filter & explore",
        caption: "Filtering by attribute narrows the layer live and surfaces tooltips on hover.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "saloni-mental-health",
    name: "Saloni Mental Health",
    tagline: "Telehealth practice site for a psychiatric NP",
    url: "https://saloni.joshjgriffith.dev",
    repoUrl: "https://github.com/vrostbyte/salonimentalhealth",
    live: true,
    stack: ["HTML", "CSS", "JavaScript", "Vercel"],
    category: "volunteer",
    status: "LIVE",
    audience: "Patients seeking psychiatric telehealth care across Arizona",
    description:
      "A professional single-page website built for Megan Presley, PMHNP-BC. She's a board-certified psychiatric nurse practitioner and U.S. Army veteran serving patients via telehealth across Arizona. Integrates with Spruce patient portal and Psychology Today for new patient intake. Built pro bono.",
    highlights: [
      "Static site, no backend needed. Clean and fast.",
      "Spruce patient portal + Psychology Today profile integration",
      "Insurance grid with sliding scale info and clear CTAs",
      "Dusty rose palette with warm, approachable medical feel",
      "Built entirely pro bono for a veteran healthcare provider",
    ],
    color: "#E879A0",
    icon: "brain",
    infra: "Static HTML/CSS/JS. No backend — still fully live.",
    screenshots: [
      { src: "/screenshots/saloni-hero.png", caption: "Hero section with warm medical branding" },
      { src: "/screenshots/saloni-services.png", caption: "Services and insurance grid" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/saloni-hero.png",
        title: "Hero",
        caption: "A patient lands on a warm, credential-forward hero section built to read as trustworthy at a glance.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/saloni-services.png",
        title: "Services & insurance",
        caption: "Services and an insurance grid answer the two questions every new patient has before they'll book: what do you treat, and will my plan cover it.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "budget-app",
    name: "Budget App",
    tagline: "A privacy-first budget projector that runs entirely in the browser",
    repoUrl: "https://github.com/vrostbyte/budget-app",
    live: false,
    stack: ["Vanilla JS", "Chart.js", "localStorage"],
    category: "app",
    status: "ARCHIVED",
    audience: "Anyone who wants a real budget projection without handing their financial data to a company's servers",
    description:
      "A budget projection tool with no account, no server, and no subscription — every number stays in the browser's localStorage. Built out of frustration with budgeting apps that want a monthly fee just to see a running balance. Projects up to 12 months ahead across income, recurring bills, one-off expenses, and debt payoff.",
    highlights: [
      "100% local storage — the data model never leaves the browser, ever",
      "A 6-step 'Guide Me' wizard walks a new user through their entire budget setup",
      "Debt payoff projections across 7 debt types, with asset-equity tracking for mortgages and auto loans",
      "Math expressions typed directly into amount fields (e.g. '1500+250')",
      "Full JSON export/import for backup and portability",
    ],
    color: "#22D3EE",
    icon: "dollar-sign",
    infra: "Single static page (HTML/CSS/JS), no backend at all — the whole point of the design.",
    screenshots: [
      { src: "/screenshots/budget-dashboard.png", caption: "Running budget with color-coded balances" },
      { src: "/screenshots/budget-wizard.png", caption: "Guide Me onboarding wizard" },
      { src: "/screenshots/budget-debt.png", caption: "Debt summary and asset equity charts" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/budget-wizard.png",
        title: "Guide Me wizard",
        caption: "A new user runs the 6-step wizard — income, debts, bills, one-off items — instead of facing a blank spreadsheet.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/budget-dashboard.png",
        title: "Running budget",
        caption: "The projection renders as a day-by-day running balance, color-coded green/orange/red so a cash-flow danger zone is visible at a glance, up to 12 months out.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/budget-debt.png",
        title: "Debt payoff",
        caption: "Debt accounts roll up into a weighted-APR summary and an estimated debt-free date, with a bar showing equity vs. balance owed on any asset-backed loan.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "mymarena",
    name: "MyMarena",
    tagline: "A barcode-scan \"is this safe to eat?\" tool for celiac and allergy diets",
    url: "https://mymarena.com",
    repoUrl: "https://github.com/vrostbyte/gluten-defender",
    live: true,
    stack: ["Next.js", "Supabase", "PWA"],
    category: "app",
    status: "LIVE",
    audience: "People managing celiac disease or a severe food allergy who need a fast answer at the grocery shelf",
    description:
      "A mobile-first installable PWA that scans a product's barcode and runs it through a gluten-and-allergy engine to answer, in seconds, whether it's safe to eat. Started life under the working name Gluten Defender; renamed MyMarena after a close family friend with a severe form of celiac disease and a dairy allergy, who was the reason the project exists. Live today as a working demo of the core scan-and-verdict loop — the fuller vision (personal journal, community-sourced verdicts) never got built out.",
    highlights: [
      "Working UPC barcode scanner feeding a real gluten/allergy verdict engine, not just a shell",
      "Named for the person it was built for — a friend with severe celiac disease and a dairy allergy",
      "Explicit product stance: decision support, never a substitute for checking the physical label",
      "Installable PWA with offline-capable service worker",
    ],
    color: "#FB923C",
    icon: "wheat",
    infra: "Next.js + Supabase on Vercel — live, functioning as a focused demo of the scan-and-verdict core rather than the full planned product.",
    screenshots: [
      { src: "/screenshots/mymarena-scan.png", caption: "Barcode scan and verdict" },
      { src: "/screenshots/mymarena-shell.png", caption: "Bottom-tab app shell" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/mymarena-scan.png",
        title: "Scan a barcode",
        caption: "Point the camera at a product's UPC — this is the working core of the app, feeding straight into the gluten/allergy engine.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/mymarena-shell.png",
        title: "Get a verdict",
        caption: "The engine returns a safe/caution/unsafe read on the product. Honest scope note: this scan-and-verdict loop is what's real today — the journal and community-verdict features from the original plan didn't get built.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "retrofit-creations",
    name: "Retrofit Creations",
    tagline: "E-commerce and custom-quote site for a custom fabrication shop",
    url: "https://retrofitcreations.com",
    repoUrl: "https://github.com/vrostbyte/retrofit-creations",
    live: true,
    stack: ["Next.js", "Supabase", "Square", "Resend", "Vercel"],
    category: "volunteer",
    status: "LIVE",
    audience: "Car culture customers and hobbyists ordering 3D-printed automotive parts, laser engraving, and CNC work",
    description:
      "Built as a volunteer for Retrofit Creations LLC, a one-person custom fabrication shop (3D printing, laser engraving, CNC carving) run solo by its owner, Hailie. The site pairs a direct-purchase storefront with a custom quote-request flow for bespoke work, plus a community section showcasing customer builds — all manageable by a non-technical solo operator. Live and processing real orders since launch; due for a design refresh.",
    highlights: [
      "First hands-on integration of Square's payments API — real purchases processed directly on the site, not a redirect to Square's hosted checkout",
      "Custom quote requests with image upload for one-off fabrication jobs",
      "Community showcase of completed customer builds and event appearances",
      "Admin panel scoped for solo, non-technical management of products, orders, and quotes",
    ],
    color: "#EF4444",
    icon: "hammer",
    infra: "Next.js + Supabase on Vercel, Square for payments — live and unaffected by the Supabase retirement that hit the personal-project apps.",
    screenshots: [
      { src: "/screenshots/retrofit-home.png", caption: "Homepage and brand identity" },
      { src: "/screenshots/retrofit-products.png", caption: "Product storefront" },
      { src: "/screenshots/retrofit-quote.png", caption: "Custom quote request flow" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/retrofit-home.png",
        title: "Storefront",
        caption: "A customer browses the storefront for ready-made parts and accessories, Square handling checkout directly.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/retrofit-quote.png",
        title: "Custom quote",
        caption: "For one-off fabrication work, a customer uploads reference images and describes the job instead of buying off a shelf.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/retrofit-products.png",
        title: "Community showcase",
        caption: "Completed builds and event appearances get featured, turning the site into a portfolio as much as a store.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "inkbound",
    name: "Inkbound",
    tagline: "A persistent-world RPG played entirely through Discord slash commands",
    repoUrl: "https://github.com/vrostbyte/inkbound",
    live: false,
    stack: ["Node.js", "discord.js", "Firebase", "Express"],
    category: "app",
    status: "ARCHIVED",
    audience: "Discord communities looking for a session-friendly RPG bot with real depth",
    description:
      "A text-based RPG bot for Discord — exploration, turn-based combat, crafting, gathering professions, a player-driven market, and a guild system, all through slash commands. Designed around short sessions (as little as 60 seconds) instead of demanding a long sit-down, with an explicit no-pay-to-win design covenant. Backed by a genuinely extensive design document set covering economy balance, bestiary, engagement design, and lore.",
    highlights: [
      "40+ slash commands covering combat, crafting, gathering, professions, market, guilds, and exploration",
      "Zero pay-to-win by design — monetization scoped to cosmetics only, enforced at the data layer",
      "Full companion design docs: economy balance, bestiary, retention mechanics, and canon lore",
      "Player-driven market economy with a taxed trading system",
    ],
    color: "#A78BFA",
    icon: "sword",
    infra: "Node.js bot process (discord.js) + Firebase for persistence, deployed via Express — not currently running. There's no web UI to screenshot (it's entirely Discord slash commands), so this one's demoed as an architecture diagram instead.",
    screenshots: [],
    diagram: {
      nodes: [
        { id: "player", label: "Player", sublabel: "Discord client", icon: "message-square", x: 8, y: 50 },
        { id: "gateway", label: "Discord Gateway", sublabel: "WebSocket", icon: "network", x: 30, y: 25 },
        { id: "bot", label: "Bot process", sublabel: "discord.js", icon: "bot", x: 52, y: 50 },
        { id: "commands", label: "Command handlers", sublabel: "combat / craft / market / guild", icon: "sword", x: 76, y: 25 },
        { id: "firestore", label: "Firestore", sublabel: "player + economy state", icon: "database", x: 76, y: 75 },
      ],
      edges: [
        { from: "player", to: "gateway" },
        { from: "gateway", to: "bot" },
        { from: "bot", to: "commands" },
        { from: "bot", to: "firestore" },
      ],
    },
    demoSteps: [
      {
        kind: "diagram",
        title: "A player types a command",
        caption: "A slash command like /explore or /attack goes through Discord's gateway to the bot process — no separate app to open, the session lives entirely inside Discord.",
        activeNodeIds: ["player", "gateway", "bot"],
        activeEdgeIndexes: [0, 1],
      },
      {
        kind: "diagram",
        title: "Routed to a handler",
        caption: "40+ command handlers cover combat, crafting, gathering, the player market, and guilds — each one a focused module, not a monolith.",
        activeNodeIds: ["bot", "commands"],
        activeEdgeIndexes: [2],
      },
      {
        kind: "diagram",
        title: "State persists",
        caption: "Player stats, inventory, and the shared market economy read/write to Firestore, so a 60-second session picks up exactly where the last one left off.",
        activeNodeIds: ["bot", "firestore"],
        activeEdgeIndexes: [3],
      },
    ],
  },
  {
    kind: "personal",
    slug: "littleboyblue",
    name: "StitchStudio",
    tagline: "A needlepoint pattern editor built for my wife's craft projects",
    repoUrl: "https://github.com/vrostbyte/littleboyblue",
    live: false,
    stack: ["Next.js", "TypeScript", "Zustand", "jsPDF"],
    category: "app",
    status: "ARCHIVED",
    audience: "My wife, for designing her own needlepoint canvases — and any needlepoint hobbyist in general",
    description:
      "A grid-based needlepoint pattern editor: draw a design with real DMC thread colors, get a unique stitch symbol assigned per color automatically, and export a print-ready PDF chart with a color key. Built because she's deep into needlepoint right now and the existing pattern tools were clunky or paywalled. Works fully offline with browser autosave — an optional Supabase connection only powers shareable links.",
    highlights: [
      "8 drawing tools (pencil, eraser, eyedropper, bucket fill, line, rect, ellipse, text stamp) with clean grid-snapping",
      "454 normalized DMC thread colors with search, and automatic unique-symbol assignment per color",
      "Full PDF export: cover page + tiled chart with symbols, color key, and instructions",
      "Runs fully offline — works with zero environment variables, Supabase only unlocks shareable links",
      "Branding overlay for a personal logo/signature on exported charts",
    ],
    color: "#60A5FA",
    icon: "scissors",
    infra: "Next.js, local-first with localStorage autosave; Supabase is optional and only needed for shareable pattern links.",
    screenshots: [
      { src: "/screenshots/stitchstudio-editor.png", caption: "Grid editor with DMC color palette" },
      { src: "/screenshots/stitchstudio-export.png", caption: "PDF chart export" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/stitchstudio-editor.png",
        title: "Design the pattern",
        caption: "She picks real DMC thread colors and draws on a grid with the same tools as a proper pixel editor — pencil, fill bucket, shapes, and a text stamp.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/stitchstudio-export.png",
        title: "Export to PDF",
        caption: "One click produces a printable chart: tiled grid pages, a stitch-symbol legend per thread color, and a cover sheet — ready to stitch from.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "diapershare",
    name: "DiaperShare",
    tagline: "A local community board for parents to share and request diapers",
    url: "https://diapershare.ai.studio/",
    repoUrl: "https://github.com/vrostbyte/diapershare",
    live: true,
    stack: ["React", "Vite", "Firebase", "Google Maps"],
    category: "app",
    status: "LIVE",
    audience: "Local parents with a diaper surplus or shortfall, in a specific community",
    description:
      "Born from a single Facebook post — offering extra diapers our baby had outgrown — that got an overwhelming response. That demand made it obvious a real, standing forum for this exchange would help more than a one-off post ever could: a map-based board where nearby parents can post what they have to give away or what they need, without every exchange depending on someone remembering to check a Facebook group.",
    highlights: [
      "Map-based browsing of nearby give/need posts via Google Maps",
      "Built directly from an observed real-world need, not a hypothetical one",
      "Firebase backend for realtime posts and community moderation",
      "A trust/legitimacy score (verified identity, address, reviews) so exchanges feel safe with strangers",
      "Location handling scoped to general area, not precise addresses, for safety",
    ],
    color: "#FCD34D",
    icon: "users",
    infra: "React + Vite frontend, Firebase (Firestore) backend, Google Maps for the location layer.",
    screenshots: [
      { src: "/screenshots/diapershare-map.png", caption: "Interactive map of nearby give/need listings and neighborhood porch hubs" },
      { src: "/screenshots/diapershare-trust.png", caption: "Community trust score breakdown" },
      { src: "/screenshots/diapershare-post.png", caption: "Posting a \"diapers to give\" listing" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/diapershare-map.png",
        title: "Browse nearby",
        caption: "A parent opens the map and sees nearby give/need listings for their neighborhood, plus a community porch hub offering 24/7 contactless drop-off.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/diapershare-trust.png",
        title: "Trust, made visible",
        caption: "Exchanging with strangers only works if it feels safe — a trust score built from verified identity, a confirmed address, diapers donated, and community reviews, all visible up front.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/diapershare-post.png",
        title: "Post in under a minute",
        caption: "Posting takes seconds: what you have or need, size, condition, and how you'd like to hand it off — the same thing that original Facebook post did, but discoverable by anyone nearby, anytime.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "bash-rpg",
    name: "bash_rpg",
    tagline: "A complete turn-based RPG, built entirely as a bash script",
    repoUrl: "https://github.com/vrostbyte/bash_rpg",
    live: false,
    stack: ["Bash"],
    category: "app",
    status: "ARCHIVED",
    audience: "Me, mostly — a for-fun exercise in how much game you can build with nothing but shell scripting",
    description:
      "A surprisingly complete terminal RPG written in pure bash: four character classes, turn-based combat, an inventory and equipment system, a shop, quests, and save/load — no runtime but bash itself. A joke taken further than it needed to go, in the best way.",
    highlights: [
      "4 character classes with full stat progression and leveling",
      "15+ enemy types across 4 exploration zones, plus boss battles",
      "Shop, quest system, inn for healing, and full inventory/equipment — in bash",
      "Colored terminal interface and working save/load, using nothing but shell built-ins",
    ],
    color: "#94A3B8",
    icon: "gamepad-2",
    infra: "A single bash script. Runs anywhere bash runs — no install, no dependencies.",
    screenshots: [
      { src: "/screenshots/bash-rpg-town.png", caption: "Character sheet and town menu" },
      { src: "/screenshots/bash-rpg-combat.png", caption: "Turn-based combat in the terminal" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/bash-rpg-town.png",
        title: "Character sheet",
        caption: "`./rpg_game.sh` drops you into character creation — Warrior, Mage, Rogue, or Paladin — then the town hub with a live HP/MP/gold HUD. This is a real captured session, not a mockup.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/bash-rpg-combat.png",
        title: "Turn-based combat",
        caption: "Exploring the forest triggers a real encounter — attack, skills, items, or flee, same as any turn-based RPG, just rendered entirely in ANSI text.",
      },
    ],
  },
  {
    kind: "personal",
    slug: "lucky-lasso-bingo",
    name: "Lucky Lasso Bingo",
    tagline: "The bingo-and-trivia platform Lucky Lasso started as, before the pivot",
    repoUrl: "https://github.com/vrostbyte/lucky-lasso-bingo",
    live: false,
    stack: ["React", "Firebase", "Tailwind CSS"],
    category: "business",
    status: "ARCHIVED",
    audience: "Event organizers running live bingo/trivia nights, plus in-room players following along on a shared screen",
    description:
      "Before Lucky Lasso LLC became a beverage-vending business, it was going to be a bingo-and-trivia events company — and this is the full platform that was built for it: game setup, live ball-pull calling, card fairness verification, payout management, and a public spectator view for the room's shared screen. The beverage-vending concept ended up being the stronger business, so this became the road not taken.",
    highlights: [
      "Full game lifecycle: setup, live ball pulls, card verification, payout tracking, game history",
      "Public spectator view separate from the host's control dashboard, for a shared venue screen",
      "Card fairness verification system — a real concern once money changes hands on a bingo win",
      "The direct predecessor to Lucky Lasso LLC's actual business, before the beverage pivot",
    ],
    color: "#FDE047",
    icon: "dice-5",
    infra: "React + Firebase (Firestore, Auth, Hosting) — still wired to a real Firebase project, so the walkthrough stops at the login screen rather than authenticating into real game data.",
    screenshots: [
      { src: "/screenshots/lasso-bingo-login.png", caption: "Host login" },
      { src: "/screenshots/lasso-bingo-dashboard.png", caption: "Host dashboard and game setup" },
      { src: "/screenshots/lasso-bingo-public.png", caption: "Public spectator view for the room screen" },
    ],
    demoSteps: [
      {
        kind: "screenshot",
        image: "/screenshots/lasso-bingo-login.png",
        title: "Host login",
        caption: "A real captured screen — the host login gate. Past this point is authenticated game data, so the rest of this walkthrough is narrated rather than screenshotted.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/lasso-bingo-dashboard.png",
        title: "Set up the game",
        caption: "A host configures a new bingo game — card patterns, payout structure — from the dashboard.",
      },
      {
        kind: "screenshot",
        image: "/screenshots/lasso-bingo-public.png",
        title: "Live on the big screen",
        caption: "During play, a separate public view projects live ball pulls to the room while the host's dashboard verifies winning cards for fairness before announcing a payout.",
      },
    ],
  },
];
